# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161122_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailitem',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='recipientAddress',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='recipientCity',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='recipientName',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='recipientState',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='recipientZip',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='senderAddress',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='senderCity',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='senderFirstName',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='senderLastName',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='senderState',
        ),
        migrations.RemoveField(
            model_name='mailitem',
            name='senderZip',
        ),
    ]
