# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161122_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailitem',
            name='recipientAddress',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='recipientCity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='recipientName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='recipientState',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='recipientZip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='senderAddress',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='senderCity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='senderFirstName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='senderLastName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='senderState',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='senderZip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
