# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161123_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailitem',
            name='recipientCountry',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='mailitem',
            name='senderCountry',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
